#include "MapManager.h"
#include "ui/CocosGUI.h"
#include "Enums.h"
#include "Player.h"
#include <iostream>
#include "Bullet.h"
#include "HudLayer.h"
#include "GameManager.h"
#include "StrategyMenu.h"
#include "Enemy.h"


USING_NS_CC;

Scene* MapManager::createScene()
{

	auto scene = Scene::create();
	auto layer = MapManager::create();

	scene->addChild(layer, 1, "MapManager");

	return scene;
}

// on "init" you need to initialize your instance
bool MapManager::init()
{
	//////////////////////////////
	// 1. super init first
	if (!Layer::init())
	{
		return false;
	}

	this->core = GameManager::getInstance();
	this->deltaTime = 0;
	/*auto random = RandomHelper::random_int(0, 5);
	if (random == 0) {
		this->createMapI();
	}
	else if (random == 1) {
		this->createMapII();
	}
	else if (random == 2) {
		this->createMapIII();
	}
	else if (random == 3) {
		this->createMapIV();
	}
	else if (random == 4) {
		this->createMapV();
	}
	else if (random == 5) {
		this->createMapVI();
	}*/

	this->createMapI();

	container = Node::create();
	this->addChild(container, 4);

	auto visibleSize = Director::getInstance()->getVisibleSize();
	auto winSize = Director::getInstance()->getWinSize();
	Vec2 origin = Director::getInstance()->getVisibleOrigin();
	Point center = Point(winSize.width + origin.x, winSize.height + origin.y);

	tile = TMXTiledMap::create("GroundMap.tmx");
	tile->setPosition(Vec2(0, 0));
	layer = tile->getLayer("Ground");
	container->addChild(tile, 1, "Mappa");

	for (int i = 0; i < MAP_WIDTH; i++) {
		for (int j = 0; j < MAP_HEIGHT; j++) {
			switch (mat[i][j])
			{
			case NONE:
				layer->setTileGID(118, Vec2(i, j));
				break;
			case GROUND:
				break;
			case WALL:
				layer->setTileGID(448, Vec2(i, j));
				break;
			case GRASS:
				layer->setTileGID(289, Vec2(i, j));
				break;
			case WATER:
				layer->setTileGID(121, Vec2(i, j));
				break;
			case GOAL:
				layer->setTileGID(400, Vec2(i, j));
				break;
			}
		}
	}

	_player = Player::create("Player.png");
	_player->setMapGame(this);
	_player->setMappa(this->getMap());
	_player->setState(IDLE);
	_player->setActualScene(EXPLORATION);
	_player->setTileMap(this->getTileMap());
	_player->setPosition(Point(32, 32));
	tile->addChild(_player);


	/*_enemy = Enemy::create("Sentry.png");
	_enemy->setState(IDLE);
	_enemy->setType(SENTRY);
	_enemy->setPosition(Point(925, 294));
	_enemy->setMapGame(this);
	_enemy->setMappa(this->getMap());
	_enemy->setTileMap(this->getTileMap());
	_enemy->setActualScene(EXPLORATION);
	_enemy->setActualWeapon(GUN);
	_enemy->setFirstDestination(Point(60, 294));
	_enemy->setSecondDestination(Point(925, 294));
	tile->addChild(_enemy, 5, "Enemy");*/

	_enemy = Enemy::create("Kamikaze.png");
	_enemy->setState(IDLE);
	_enemy->setType(KAMIKAZE);
	_enemy->setPosition(Point(400, 294));
	_enemy->setMapGame(this);
	_enemy->setMappa(this->getMap());
	_enemy->setTileMap(this->getTileMap());
	_enemy->setActualScene(EXPLORATION);
	tile->addChild(_enemy, 5, "Enemy");


	hud = new HudLayer();
	this->addChild(hud, 15);

	// Register Touch Event
	auto dispatcher = Director::getInstance()->getEventDispatcher();
	auto listener = EventListenerTouchOneByOne::create();

	listener->onTouchBegan = CC_CALLBACK_2(MapManager::onTouchBegan, this);
	listener->onTouchEnded = CC_CALLBACK_2(MapManager::onTouchEnded, this);

	dispatcher->addEventListenerWithSceneGraphPriority(listener, this);

	log("WELCOME IN MY GAME. YOU HAVE TO REACH THE GOAL (THE STAIRS) TO WIN IT. GOOD LUCK!");

	_player->setMatrix();
	_player->solve((int)_player->getPosition().x, (int)_player->getPosition().y);

	_player->setTarget(_enemy);

	_enemy->setTarget(_player);
	
	this->scheduleUpdate();
	_player->scheduleUpdate();
	_enemy->scheduleUpdate();

	return true;
}

void MapManager::update(float dt)
{
	auto visibleSize = Director::getInstance()->getVisibleSize();
	Vec2 origin = Director::getInstance()->getVisibleOrigin();
    deltaTime += dt;

	auto mappa = this->getMap();
	auto tileCoord = this->tileCoordForPosition(_player->getPosition());

	if (deltaTime >= 1.0f) {

		Point position = _player->getPosition();

		Size winSize = Director::getInstance()->getWinSize();

		int x = MAX(position.x, winSize.width / 2);
		int y = MAX(position.y, winSize.height / 2);
		x = MIN(x, (MAP_SIZE_WIDTH)-winSize.width / 2);
		y = MIN(y, (MAP_SIZE_HEIGHT)-winSize.height / 2);
		Point actualPosition = Point(x, y);

		Point centerOfView = Point(winSize.width / 2, winSize.height / 2);
		Point viewPoint = Point(centerOfView) - Point(actualPosition);
		container->runAction(MoveTo::create(0.999f, Vec2(viewPoint.x, viewPoint.y)));
		deltaTime = 0;
	}

}


bool MapManager::onTouchBegan(Touch *touch, Event *event)
{
	return true;
}


void MapManager::onTouchEnded(Touch *touch, Event *event)
{	
	if (core->inPause()) {
		core->resumeGame();
		return;
	}
	core->pauseGame();
	return;
}

Point MapManager::tileCoordForPosition(Point position)
{
	int x = position.x / TILE_WIDTH;
	int y = (MAP_SIZE_HEIGHT - position.y) / TILE_HEIGHT;
	return Point(x, y);
}

Point MapManager::positionCoordForTile(Point position)
{
	int x = position.x * TILE_WIDTH;
	int y = MAP_SIZE_HEIGHT - position.y * TILE_HEIGHT;
	return Point(x, y);
}

void MapManager::createMapI() {

	mat = new int*[MAP_WIDTH];
	for (int i = 0; i < MAP_WIDTH; ++i)
		mat[i] = new int[MAP_HEIGHT];

	int random = RandomHelper::random_int(GROUND, WATER);
	int random2 = RandomHelper::random_int(GROUND, WATER);
	int random3 = RandomHelper::random_int(GROUND, WATER);

	int map[MAP_WIDTH][MAP_HEIGHT] = {
		{ WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, WALL, WALL, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, WALL, WALL, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, WALL, WALL, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GOAL, WALL },
		{ WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL }
	};

	for (int i = 0; i < MAP_WIDTH; i++) {
		for (int j = 0; j < MAP_HEIGHT; j++) {
			mat[i][j] = map[i][j];
		}
	}
}

void MapManager::createMapII() {

	mat = new int*[MAP_WIDTH];
	for (int i = 0; i < MAP_WIDTH; ++i)
		mat[i] = new int[MAP_HEIGHT];

	int random = RandomHelper::random_int(GROUND, WATER);
	int random2 = RandomHelper::random_int(GROUND, WATER);
	int random3 = RandomHelper::random_int(GROUND, WATER);

	int map[MAP_WIDTH][MAP_HEIGHT] = {
		{ WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL},
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, WALL, GROUND, WALL, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, WALL, WALL, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, WALL, WALL, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, WALL, WALL, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, WALL, WALL, WALL, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, WALL, WALL, WALL, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, WALL, WALL, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, WALL, WALL, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, WALL, WALL, WALL, WALL, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, WALL, WALL, WALL, WALL, WALL, WALL, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, WALL, WALL, WALL, WALL, WALL, WALL, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, WALL, WALL, GROUND, WALL, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, WALL, GROUND, WALL, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, WALL, GROUND, WALL, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, WALL, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, WALL, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, WALL, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, WALL, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, WALL, WALL, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, WALL, GROUND, WALL, WALL, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, WALL, WALL, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, WALL, WALL, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GOAL, WALL },
		{ WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL}
	};

	for (int i = 0; i < MAP_WIDTH; i++) {
		for (int j = 0; j < MAP_HEIGHT; j++) {
			mat[i][j] = map[i][j];
		}
	}
}

void MapManager::createMapIII() {

	mat = new int*[MAP_WIDTH];
	for (int i = 0; i < MAP_WIDTH; ++i)
		mat[i] = new int[MAP_HEIGHT];

	int random0 = RandomHelper::random_int(GROUND, GRASS);
	int random1 = RandomHelper::random_int(GROUND, WATER);
	int random2 = RandomHelper::random_int(NONE, WALL);
	int random3 = RandomHelper::random_int(NONE, WATER);

	int map[MAP_WIDTH][MAP_HEIGHT] = {
		{ WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, random1, random1, random1, random1, random1, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, random1, random1, random1, random1, random1, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, random1, random1, random1, random1, random1, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, random1, random1, random1, random1, random1, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, random1, random1, random1, random1, random1, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, random3, GROUND, random3, random3, random3, random3, random3, random3, random3, random3, random3, random3, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, random3, GROUND, random3, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, random3, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, random3, GROUND, random3, GROUND, random3, random3, random3, random3, random3, random3, GROUND, random3, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, random3, GROUND, random3, GROUND, random3, GROUND, GROUND, GROUND, GROUND, random3, GROUND, random3, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, random3, GROUND, random3, GROUND, random3, GROUND, random3, random3, GROUND, random3, GROUND, random3, GROUND, GROUND, GROUND, GROUND, GRASS, GRASS, GRASS, GRASS, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, random2, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, random3, GROUND, random3, GROUND, random3, GROUND, random3, random3, GROUND, random3, GROUND, random3, GROUND, GROUND, GROUND, GROUND, GRASS, GRASS, GRASS, GRASS, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, random2, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, random3, GROUND, random3, GROUND, random3, GROUND, random3, random3, GROUND, random3, GROUND, random3, GROUND, GROUND, GROUND, GROUND, GRASS, GRASS, GRASS, GRASS, GRASS, GROUND, GROUND, GROUND, random2, GROUND, GROUND, GROUND, random2, GROUND, GROUND, random2, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, random3, GROUND, random3, GROUND, random3, GROUND, random3, random3, GROUND, random3, GROUND, random3, GROUND, GROUND, GROUND, GROUND, GRASS, GRASS, GRASS, GRASS, GRASS, GROUND, GROUND, GROUND, GROUND, random2, GROUND, GROUND, random2, GROUND, random2, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, random3, GROUND, random3, GROUND, random3, GROUND, random3, random3, GROUND, random3, GROUND, random3, GROUND, GROUND, GROUND, GROUND, GRASS, GRASS, GRASS, GRASS, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, random2, random2, random2, random2, random2, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, random3, GROUND, random3, GROUND, random3, GROUND, GROUND, random3, GROUND, random3, GROUND, random3, GROUND, GROUND, GROUND, GROUND, GRASS, GRASS, GRASS, GRASS, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, random2, random2, random2, random2, random2, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, random3, GROUND, random3, GROUND, random3, random3, random3, random3, GROUND, random3, GROUND, random3, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, random2, random2, random2, random2, random2, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, random3, GROUND, random3, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, random3, GROUND, random3, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, random2, GROUND, GROUND, random2, GROUND, GROUND, random2, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, random3, GROUND, random3, random3, random3, random3, random3, random3, random3, random3, GROUND, random3, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, random2, GROUND, GROUND, GROUND, random2, GROUND, GROUND, GROUND, random2, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, random3, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, random3, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, random2, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, random3, random3, random3, random3, random3, random3, random3, random3, random3, random3, random3, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, WALL, WALL, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, WALL, WALL, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, WALL, WALL, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GOAL, WALL },
		{ WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL }
	};

	for (int i = 0; i < MAP_WIDTH; i++) {
		for (int j = 0; j < MAP_HEIGHT; j++) {
			mat[i][j] = map[i][j];
		}
	}
}


void MapManager::createMapIV() {

	mat = new int*[MAP_WIDTH];
	for (int i = 0; i < MAP_WIDTH; ++i)
		mat[i] = new int[MAP_HEIGHT];

	int random0 = RandomHelper::random_int(GROUND, GRASS);
	int random1 = RandomHelper::random_int(GROUND, WATER);
	int random2 = RandomHelper::random_int(NONE, WALL);
	int random3 = RandomHelper::random_int(NONE, WATER);

	int map[MAP_WIDTH][MAP_HEIGHT] = {
		{ WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, GROUND, GROUND, GROUND, random1, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, GROUND, GROUND, GROUND, GROUND, random1, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, GROUND, GROUND, GROUND, random1, GROUND, random1, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, GROUND, GROUND, GROUND, GROUND, random1, GROUND, random1, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, GROUND, GROUND, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, GROUND, GROUND, GROUND, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, random2, GROUND, GROUND, GROUND, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, random3, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, random3, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, random3, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, random3, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, random3, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, random3, GROUND, GROUND, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, GROUND, GROUND, GROUND, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, GROUND, WALL },
		{ WALL, GROUND, random3, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, GROUND, WALL },
		{ WALL, random3, GROUND, GROUND, GROUND, GROUND, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, GROUND, WALL },
		{ WALL, random3, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, random1, GROUND, random1, GROUND, random1, GROUND, GROUND, WALL },
		{ WALL, GROUND, random3, GROUND, GROUND, GROUND, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, random1, GROUND, random1, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, random3, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, random1, GROUND, random1, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, random3, GROUND, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, random1, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, random3, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, random1, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, random3, GROUND, GROUND, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, random3, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, random3, GROUND, GROUND, GROUND, GROUND, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, random3, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, random3, GROUND, GROUND, GROUND, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, random0, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, WALL, WALL, WALL },
		{ WALL, GROUND, GROUND, random3, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, random3, GROUND, GROUND, GROUND, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, random3, GROUND, GROUND, GROUND, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, WALL, WALL, GROUND, WALL },
		{ WALL, GROUND, GROUND, random3, GROUND, GROUND, GROUND, GROUND, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, random3, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, WALL, WALL, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GOAL, WALL },
		{ WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL }
	};

	for (int i = 0; i < MAP_WIDTH; i++) {
		for (int j = 0; j < MAP_HEIGHT; j++) {
			mat[i][j] = map[i][j];
		}
	}
}

void MapManager::createMapV() {

	mat = new int*[MAP_WIDTH];
	for (int i = 0; i < MAP_WIDTH; ++i)
		mat[i] = new int[MAP_HEIGHT];

	int random0 = RandomHelper::random_int(GROUND, GRASS);
	int random1 = RandomHelper::random_int(GROUND, WATER);
	int random2 = RandomHelper::random_int(NONE, WALL);
	int random3 = RandomHelper::random_int(NONE, WATER);

	int map[MAP_WIDTH][MAP_HEIGHT] = {
		{ WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL },
		{ WALL, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random2, random2, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, random0, GRASS, random0, GRASS, random0, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random2, random2, random2, random2, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, random0, GRASS, random0, GRASS, random0, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, random2, random2, random2, random2, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, random0, GRASS, random0, GRASS, random0, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, random2, random2, random2, random2, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, random0, GRASS, random0, GRASS, random0, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, random2, random2, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, random0, GRASS, random0, GRASS, random0, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, random0, GRASS, random0, GRASS, random0, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, random0, GRASS, random0, GRASS, random0, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, random0, GRASS, random0, GRASS, random0, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, random0, GRASS, random0, GRASS, random0, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, random0, GRASS, random0, GRASS, random0, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, random0, GRASS, random0, GRASS, random0, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, random0, GRASS, random0, GRASS, random0, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, random0, GRASS, random0, GRASS, random0, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, random0, GRASS, random0, GRASS, random0, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, random0, GRASS, random0, GRASS, random0, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, random2, random2, random2, random2, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, random0, GRASS, random0, GRASS, random0, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, random2, random2, random2, random2, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, random0, GRASS, random0, GRASS, random0, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, random2, random2, random2, random2, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, random0, GRASS, random0, GRASS, random0, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, random2, random2, random2, random2, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, random0, GRASS, random0, GRASS, random0, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, random2, random2, random2, random2, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random3, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, random0, GRASS, random0, GRASS, random0, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random3, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, random0, GRASS, random0, GRASS, random0, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, random3, GRASS, GRASS, GRASS, GRASS, random3, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, random0, GRASS, random0, GRASS, random0, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random3, GRASS, GRASS, GRASS, random3, GRASS, GRASS, GRASS, random3, GRASS, GRASS, WALL },
		{ WALL, GRASS, random0, GRASS, random0, GRASS, random0, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random3, GRASS, GRASS, random3, GRASS, GRASS, random3, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random3, GRASS, random3, GRASS, random3, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random3, random3, random3, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random3, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random3, GRASS, random3, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, random0, random0, random0, random0, random0, random0, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random3, GRASS, GRASS, GRASS, random3, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, random0, random0, random0, random0, random0, random0, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random3, GRASS, GRASS, GRASS, GRASS, GRASS, random3, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, random3, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random3, GRASS, WALL },
		{ WALL, GRASS, random0, random0, random0, random0, random0, random0, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, random0, random0, random0, random0, random0, random0, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, random2, random2, random2, random2, random2, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random1, GRASS, GRASS, GRASS, GRASS, GRASS, random2, random2, random2, random2, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, random0, random0, random0, random0, random0, random0, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random2, random2, random2, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, random0, random0, random0, random0, random0, random0, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random2, random2, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, random2, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL }
	};

	for (int i = 0; i < MAP_WIDTH; i++) {
		for (int j = 0; j < MAP_HEIGHT; j++) {
			mat[i][j] = map[i][j];
		}
	}
}

void MapManager::createMapVI() {

	mat = new int*[MAP_WIDTH];
	for (int i = 0; i < MAP_WIDTH; ++i)
		mat[i] = new int[MAP_HEIGHT];

	int random0 = RandomHelper::random_int(GROUND, GRASS);
	int random1 = RandomHelper::random_int(GROUND, WATER);
	int random2 = RandomHelper::random_int(NONE, WALL);
	int random3 = RandomHelper::random_int(NONE, WATER);

	int map[MAP_WIDTH][MAP_HEIGHT] = {
		{ WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL },
		{ WALL, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GRASS, GRASS, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GRASS, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GRASS, GRASS, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GRASS, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GRASS, GRASS, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GRASS, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GRASS, GRASS, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GRASS, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GRASS, GRASS, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GRASS, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GRASS, GRASS, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GRASS, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GRASS, GRASS, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GRASS, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GRASS, GRASS, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GRASS, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GRASS, GRASS, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GRASS, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GRASS, GRASS, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GRASS, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GRASS, GRASS, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GRASS, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GRASS, GRASS, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GRASS, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GRASS, GRASS, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GRASS, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GRASS, GRASS, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GRASS, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GRASS, GRASS, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GRASS, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GRASS, GRASS, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GRASS, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GRASS, WATER, WATER, WATER, WATER, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GRASS, WATER, WATER, WATER, WATER, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GRASS, WATER, WATER, WATER, WATER, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GRASS, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GRASS, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GRASS, WATER, WATER, WATER, WATER, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GRASS, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GRASS, WALL },
		{ WALL, GROUND, GROUND, GROUND, random0, random0, random0, random0, random0, random0, random0, GRASS, WATER, WATER, WATER, WATER, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GRASS, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GRASS, WALL },
		{ WALL, GROUND, GROUND, GROUND, random0, random1, random1, random1, random1, random1, random0, GRASS, WATER, WATER, WATER, WATER, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
		{ WALL, GROUND, GROUND, GROUND, random0, random1, random1, random1, random1, random1, random0, GRASS, WATER, WATER, WATER, WATER, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, random0, random1, random1, random1, random1, random1, random0, GRASS, WATER, WATER, WATER, WATER, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, random0, random1, random1, random1, random1, random1, random0, GRASS, WATER, WATER, WATER, WATER, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, random0, random1, random1, random1, random1, random1, random0, GRASS, WATER, WATER, WATER, WATER, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, random0, random1, random1, random1, random1, random1, random0, GRASS, WATER, WATER, WATER, WATER, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, random0, random1, random1, random1, random1, random1, random0, GRASS, WATER, WATER, WATER, WATER, GRASS, GROUND, GROUND, GROUND, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, random0, random0, random0, random0, random0, random0, random0, GRASS, WATER, WATER, WATER, WATER, GRASS, GROUND, GROUND, GROUND, GRASS, WATER, WATER, WATER, WATER, GRASS, GROUND, GROUND, GROUND, random3, random3, random3, random3, random3, random3, random3, random3, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GRASS, WATER, WATER, WATER, WATER, GRASS, GROUND, GROUND, GROUND, GRASS, WATER, WATER, WATER, WATER, GRASS, GROUND, GROUND, GROUND, GROUND, random3, random2, random2, random2, random2, random2, random2, random3, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GRASS, WATER, WATER, WATER, WATER, GRASS, GROUND, GROUND, GROUND, GRASS, WATER, WATER, WATER, WATER, GRASS, GROUND, GROUND, GROUND, GROUND, random3, random2, random2, random2, random2, random2, random2, random3, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GRASS, WATER, WATER, WATER, WATER, GRASS, GROUND, GROUND, GROUND, GRASS, WATER, WATER, WATER, WATER, GRASS, GROUND, GROUND, GROUND, GROUND, random3, random2, random2, random2, random2, random2, random2, random3, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GRASS, WATER, WATER, WATER, WATER, GRASS, GROUND, GROUND, GROUND, GRASS, WATER, WATER, WATER, WATER, GRASS, GROUND, GROUND, GROUND, GROUND, random3, random3, random3, random3, random3, random3, random3, random3, WALL, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GROUND, GROUND, GROUND, GRASS, GRASS, GRASS, GRASS, GRASS, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, WALL, WALL, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GROUND, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, WALL, WALL, WALL },
		{ WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL, GROUND, GROUND, GOAL, WALL },
		{ WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL }
	};

	for (int i = 0; i < MAP_WIDTH; i++) {
		for (int j = 0; j < MAP_HEIGHT; j++) {
			mat[i][j] = map[i][j];
		}
	}
}


int** MapManager::getMap() {
	return mat;
}

TMXTiledMap* MapManager::getTileMap() {
	return tile;
}

void MapManager::setStrategyMenu(StrategyMenu* strategy) {
	this->strategy = strategy;
}

void MapManager::setPlayer(Player* player) {
	this->_player = player;
}

Player* MapManager::getPlayer() {
	return this->_player;
}

void MapManager::beginBattle(Enemy* enemy) {
	GameManager::getInstance()->startBattle(enemy, _player);
	tile->removeChild(enemy);
	return;
}
